services:
  - type: web
    name: dia-d
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn run:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: electoral_secret_key_2024_muy_segura
      - key: JWT_SECRET_KEY
        value: jwt_secret_key_2024_muy_segura
      - key: DATABASE_URL
        value: sqlite:///electoral.db
      - key: PYTHONUNBUFFERED
        value: "1"
